AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Exclude:
    - 'lazy_record.gemspec'
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lazy_record.gemspec'
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
