Metrics/LineLength:
  Exclude:
    - 'lazy_record.gemspec'
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lazy_record.gemspec'
    - 'spec/**/*'

Security/Eval:
  Exclude:
    - 'spec/spec_helper.rb'


AllCops:
  TargetRubyVersion: 2.4.1